source 'http://rubygems.org'

gem 'rails', '=3.2.3'
gem 'sqlite3', '=1.3.6'
gem "makandra_resource_controller", :path => "../"

gem 'redgreen', '=1.2.2'

group :test do
  gem "shoulda", '=3.0.1'
  gem "mocha", '=0.9.9'
  gem "ruby-debug", '=0.10.4'
end
